---
- name: Install Ansible Docker prereqs
  hosts: all
  gather_facts: false
  become: yes
  tags:
    - docker
  tasks:
    - name: Update repositories cache and install "pip" packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - python3-pip

    - name: Ensure ansible docker prereqs are installed
      pip:
        name:
          - docker >= 1.20
          - pyyaml >= 3.11
          - docker-compose >= 1.7.0

- name: Deploy services
  hosts: all
  gather_facts: false
  become: yes
  tags:
    - deploy
  tasks:
    - name: make nimbus dir 
      file:
        path: "{{ nimbus_dir }}"
        state: directory
        mode: 0755
    
    - name: make nimbus data dir
      file: 
        path : "{{ nimbus_data_dir }}"
        state: directory
        mode: 0755

    - name: copy
      template:
        src: "templates/{{ item }}"
        dest: "{{ nimbus_dir }}"
      loop:
        - .env
        - docker-compose.yml

    - name: start compose
      docker_compose:
        project_src: "{{ nimbus_dir }}"
        pull: yes
        remove_orphans: yes
        debug: yes
      register: output

- name: Set backup on machines
  hosts: all
  gather_facts: false
  become: yes
  tags:
    - backup
  tasks:
    - name: Create backup folder if it does not exist
      file:
        path: "{{ nimbus_backup_data_dir }}"
        state: directory
        mode: 0755
    - name: Setup cron job
      template:
        src: "templates/nimbus_backup.sh"
        dest: "/etc/cron.daily/nimbusBackup"
        mode: 0751